import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Research submodules are validated with their own toolchains.
    "research/upstream/**",
    // Manual site build outputs are regenerated by each build-site.sh.
    "docs/user-manual/**/.vitepress/dist/**",
    "docs/user-manual/**/.vitepress/cache/**",
  ]),
]);

export default eslintConfig;
